### ISSUE TITLE
Documenting `conflict_of`, the case when syncing an updated item without first obtaining sync_token

### ISSUE THREAD

**Issue by fasiha** [standardfile/standardfile.github.io#9]
I love the idea of Standard File, thank you for your hard work on it!!!

I’m implementing a TypeScript client (this was before I saw https://github.com/standardfile/sfjs doh!) and I see something a little unexpected when I do the following:

1. login
2. immediately sync, submitting one fresh item (with new `uuid`) without first obtaining `sync_token`
3. restart client
4. login again
5. immediately sync an *updated* version of the same item (same `uuid` & `create_time`, but different `update_time` and contents), without first obtaining `sync_token`.

In the server response to (5), I see the updated item returned in the `saved_items` array, but I also see a brand new item in the `retrieved_items` array: it’s the same contents as the original item (from (2) above) but with a brand new `uuid` like 3e2a4949-776c-4f93-8eb2-60bb65985684 as well as a new field, `conflict_of: '<original item uuid here>'`.

Then, if I login and sync again, I see two items, the updated one as well as the original (under a new server-generated uuid), except the latter lacks the `conflict_of` field. Since the latter is the same as the original document, I can decrypt it if I ignore the new `uuid`.

(Of course, I only ran into this because I was experimenting. I now see that, if I first sync (not updating anything), save the `sync_token`, and then push updated items, Standard File just overwrites the old items and I don’t get any extra server-generated items. That’s obviously the right way for a client to do updates.)

In rereading the discussion of `saved_items` at https://standardfile.org in light of the above, I think I understand better what `saved_items` means: these are items that were submitted to the server, and furthermore, if you submit an item that will overwrite an existing item *without* proving that you’ve seen it’s previous version (i.e., without a `sync_token` from *after* the existing item was submitted), then the server is smart and will back up that existing item with a new random `uuid` and send the backup to the client, with a one-time `conflict_of` field, under `retrieved_items`.

A side question is, is this backup behavior part of the spec or should it be treated as a special feature of the https://sync.standardnotes.org server? If it’s part of the spec, I can draft a small emendation to the discussion of `retrieved_items` and `saved_items` that reflect this behavior. (It reminds me of how CouchDB does things—each item has a revision number and when you update an item, you have to submit its old revision number to prove to the server that you had the latest version. They do this to greatly simplify syncing and conflict resolution between multiple instances.)

**Comment by mobitar** [comment]
So the current SF spec mostly deals with the encryption and some of the REST API, but doesn't full capture the server-side API. Namely what's missing is, as you've noticed, the conflict resolution.

If you try to save an item for which there is already a pending change on the server, the item will be duplicated and returned with a new UUID, and will be marked `conflict_of` the other item.

There's also other things that aren't documented, like how to generate a sync token, etc. 

The main reason is that the ruby-server implementation is the de-facto implementation, and I wanted to see how it would evolve over time before documenting in depth on how to build your own SF server implementation from scratch. So far, it hasn't changed much, so it might be due to expand the documentation.

>  I can draft a small emendation to the discussion of retrieved_items and saved_items that reflect this behavior.

Yes, sure, this might be a good first step to expanding the docs.

**Comment by mobitar** [comment]
Because UUIDs are now tied to the encrypted ciphertext, the server can no longer duplicate items and give them a new UUID, so the server now defers conflict resolution to the client. `conflict_of` is no longer used.
